FROM seffeng/python

ENV PACKAGE=""\
 EXTEND="chromium-chromedriver"

RUN apk update &&\
 apk add --no-cache ${EXTEND}  &&\
 pip install selenium &&\
 cd /tmp &&\
 rm -rf /var/cache/apk/* &&\
 rm -rf /tmp/*
