FROM seffeng/python

ENV PACKAGE="gcc"\
 EXTEND="libffi-dev libxml2-dev libxslt-dev python3-dev libc-dev py3-wheel py3-trustme"

RUN apk update &&\
 apk add --no-cache ${PACKAGE} ${EXTEND}  &&\
 pip install scrapy &&\
 apk del ${PACKAGE} &&\
 cd /tmp &&\
 rm -rf /var/cache/apk/* &&\
 rm -rf /tmp/*
